// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Emotion = /* module */[];

var Express = /* module */[];

exports.Emotion = Emotion;
exports.Express = Express;
/* No side effect */
