// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Udp = 0;

var Utils = 0;

var Server = 0;

var Template = 0;

exports.Udp = Udp;
exports.Utils = Utils;
exports.Server = Server;
exports.Template = Template;
/* No side effect */
